config/routes.rb
NcaaPool::Application.routes.draw do
  devise_for :users

  root 'users#show'

  resources :drafts
  resources :users
  resources :teams
  post "teams/draft", :to => "teams#draft"

  

end

app/models/conference.rb
class Conference < ActiveRecord::Base
end

app/models/draft.rb
class Draft < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :teams, :foreign_key => :owner_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :authenticate_user!
	before_filter :init
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def init
  	@current_draft = Draft.where("YEAR(year) = ?", Date.today.year).first
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
	def show
		@available_teams = Team.where(:owner_id => nil)
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = current_user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drafts/show.html.erb
<%= render "layouts/header" %>
<div class="col-md-2"></div>
<div class="col-md-8">
	<%= form_for :team, :url => teams_draft_path do |f| %>
		<%= f.label :id, "Avaialable Teams" %>
		<%= select("team", "id", Team.all.where("owner_id IS NULL").collect {|p| [ p.name, p.id ] }, {include_blank: 'None'}) %>
	<% end %>
</div>
<div class="col-md-2"></div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "NCAA Pick'em Pool", root_path, :class => "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav">
        <li><a href="#">Standings</a></li>
        <li><%= link_to "Draft Lobby", draft_path(@current_draft.id) %></li>
        <li><%= link_to "My Teams", "#" %></li>
      </ul>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to current_user.email, "#" %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NcaaPool</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="row">
			<%= yield %>
	</div>

</body>
</html>

app/views/users/show.html.erb
<%= render "layouts/header" %>
<div class="col-md-2"></div>
<div class="col-md-8">
	
</div>
<div class="col-md-2"></div>